name: Sambhav

on: 
push : 
branches:[ main ]
pull_request:
branchec:[ main ]

workflow_dispatch:

jobs:

build:

runs-on: ubuntu-latest

setps:

- uses: actions/checkout@v3

  name: Set Up npm
  uses: actions/setup-node@v3
  with:
  node-version: 16
  